name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build
      run: mkdir build && cd build && cmake .. -G Ninja && cmake --build . -j $(nproc)    
    - name: test
      run: ctest --output-on-failure
