name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup-thirdparty
      run: scripts/setup_thirdparty.sh
    - name: build
      run: scripts/build.sh
    - name: tests
      run: scripts/run_tests.sh
